spring:
  application:
    name: service-a
  config:
    import: optional:configserver:http://localhost:8888
app:
  title: Service HHH
  username: user-a
  pass: 1234567
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: refresh
